version = 1

[[analyzers]]
name = "javascript"

[analyzers.meta]
environment = [
    "nodejs",
    "vitest"
]

[[analyzers]]
name = "docker"

[analyzers.meta]
dockerfile_paths = ["./Dockerfile"]

[[analyzers]]
name = "test-coverage"

[[analyzers]]
name = "sql"
