version = 1
test_patterns = [
    "./**/*.spec.ts",
    "./**/*.test.ts"
]

[[analyzers]]
name = "javascript"
enable = true

[analyzers.meta]
environment = [
    "nodejs",
    "vitest"
]

[[analyzers]]
name = "docker"
enable = false

[analyzers.meta]
dockerfile_paths = ["./Dockerfile"]

[[analyzers]]
name = "sql"
enable = false
