version = 1

[[analyzers]]
name = "javascript"

[analyzers.meta]
plugins = ["react"]
environment = [
    "browser",
    "vitest"
]

[[analyzers]]
name = "docker"

[analyzers.meta]
dockerfile_paths = ["./Dockerfile"]

[[analyzers]]
name = "test-coverage"
